[package]
name = "demagnetize"
version = "0.1.0-dev"
edition = "2021"
rust-version = "1.70"
description = "Convert magnet links to .torrent files"
authors = ["John Thorvald Wodder II <demagnetize-rs@varonathe.org>"]
repository = "https://github.com/jwodder/demagnetize-rs"
documentation = "https://github.com/jwodder/demagnetize-rs"
license = "MIT"
keywords = []
# See <https://crates.io/category_slugs> for a list of categories
categories = []
exclude = ["/.*"]

[dependencies]
bytes = "1.4.0"
data-encoding = "2.4.0"
log = "0.4.19"
rand = "0.8.5"
rand_distr = "0.4.3"
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["macros", "sync", "rt", "rt-multi-thread", "time"] }
url = "2.4.0"
